global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'settle_api'
    static_configs:
      - targets: ['192.168.1.72:4725']

  - job_name: node
    static_configs:
      - targets: [ 'node-exporter:9100' ]
